recipes.remove(<mysticalagriculture:crafting:16>);
mods.botania.ManaInfusion.addInfusion(<mysticalagriculture:crafting:16>, <ore:seed>, 1000);
recipes.remove(<mysticalagriculture:infusion_crystal>);
recipes.remove(<mysticalagriculture:master_infusion_crystal>);
recipes.addShaped(<mysticalagradditions:insanium>, [[<projecte:item.pe_matter:1>, <mysticalagriculture:crafting:4>, <projecte:item.pe_matter:1>],[<mysticalagriculture:crafting:4>, <projecte:item.pe_philosophers_stone>, <mysticalagriculture:crafting:4>], [<projecte:item.pe_matter:1>, <mysticalagriculture:crafting:4>, <projecte:item.pe_matter:1>]]);
recipes.addShaped(<mysticalagriculture:crafting:4>, [[<projecte:item.pe_matter:1>, <mysticalagriculture:crafting:3>, <projecte:item.pe_matter:1>],[<mysticalagriculture:crafting:3>, <projecte:item.pe_philosophers_stone>, <mysticalagriculture:crafting:3>], [<projecte:item.pe_matter:1>, <mysticalagriculture:crafting:3>, <projecte:item.pe_matter:1>]]);
recipes.addShaped(<mysticalagriculture:crafting:3>, [[<projecte:item.pe_matter:1>, <mysticalagriculture:crafting:2>, <projecte:item.pe_matter:1>],[<mysticalagriculture:crafting:2>, <projecte:item.pe_philosophers_stone>, <mysticalagriculture:crafting:2>], [<projecte:item.pe_matter:1>, <mysticalagriculture:crafting:2>, <projecte:item.pe_matter:1>]]);
recipes.addShaped(<mysticalagriculture:crafting:2>, [[<projecte:item.pe_matter:1>, <mysticalagriculture:crafting:1>, <projecte:item.pe_matter:1>],[<mysticalagriculture:crafting:1>, <projecte:item.pe_philosophers_stone>, <mysticalagriculture:crafting:1>], [<projecte:item.pe_matter:1>, <mysticalagriculture:crafting:1>, <projecte:item.pe_matter:1>]]);
recipes.addShaped(<mysticalagriculture:crafting:1>, [[<projecte:item.pe_matter:1>, <mysticalagriculture:crafting>, <projecte:item.pe_matter:1>],[<mysticalagriculture:crafting>, <projecte:item.pe_philosophers_stone>, <mysticalagriculture:crafting>], [<projecte:item.pe_matter:1>, <mysticalagriculture:crafting>, <projecte:item.pe_matter:1>]]);
